const PDFDocument = require('pdfkit')
const { calculateExposure, calculateROI, calculateInsuranceGap } = require('./financialCalculator')

function formatMoney(amount) {
  return '$' + amount.toLocaleString('en-US')
}

async function generateBoardReport({ org, scenario, compromisedEmployees, events, insuranceLimit = 2000000 }) {
  return new Promise((resolve, reject) => {
    const chunks = []
    const doc = new PDFDocument({ margin: 50, size: 'A4' })

    doc.on('data', chunk => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const exposure = calculateExposure({
      compromisedEmployees,
      attackTypes: scenario.attackTypes,
      industry: org.industry
    })
    const insuranceGap = calculateInsuranceGap({ totalExposure: exposure.totalExposure, insuranceLimit })

    // Header
    doc.fontSize(20).fillColor('#0f172a').text('CYBERSECURITY RISK BRIEFING', { align: 'center' })
    doc.fontSize(12).fillColor('#64748b').text(`${org.name} — Confidential Board Report`, { align: 'center' })
    doc.moveDown()
    doc.fontSize(10).fillColor('#94a3b8').text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, { align: 'center' })
    doc.moveDown(2)

    // Divider
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#1e40af').lineWidth(2).stroke()
    doc.moveDown()

    // Executive Summary
    doc.fontSize(14).fillColor('#1e40af').text('EXECUTIVE SUMMARY')
    doc.moveDown(0.5)
    doc.fontSize(10).fillColor('#1e293b')
    doc.text(`Scenario: ${scenario.name}`)
    doc.text(`Status: ${scenario.status.toUpperCase()}`)
    doc.text(`Employees targeted: ${scenario.targetEmployees?.length || 0}`)
    doc.text(`Employees compromised: ${scenario.compromisedCount}`)
    doc.text(`Employees who reported: ${scenario.reportedCount}`)
    doc.text(`Ghost state: ${scenario.ghostState}`)
    doc.moveDown(1.5)

    // Financial Exposure
    doc.fontSize(14).fillColor('#dc2626').text('FINANCIAL EXPOSURE')
    doc.moveDown(0.5)
    doc.fontSize(24).fillColor('#dc2626').text(formatMoney(exposure.totalExposure), { align: 'center' })
    doc.fontSize(10).fillColor('#64748b').text('Simulated financial exposure based on IBM/Verizon/FBI IC3 breach cost data', { align: 'center' })
    doc.moveDown()

    doc.fontSize(10).fillColor('#1e293b')
    doc.text(`Industry multiplier (${org.industry}): ${exposure.multiplier}x`)
    doc.text(`Insurance limit: ${formatMoney(insuranceLimit)}`)
    doc.text(`Coverage gap: ${formatMoney(insuranceGap.coverageGap)}`)
    doc.text(`Gap status: ${insuranceGap.gapLabel}`)
    doc.moveDown(1.5)

    // Kill Chain Summary
    doc.fontSize(14).fillColor('#1e40af').text('ATTACK CHAIN SUMMARY')
    doc.moveDown(0.5)
    const ghostHops = events.filter(e => e.isGhostHop).sort((a, b) => a.hopNumber - b.hopNumber)
    if (ghostHops.length > 0) {
      ghostHops.forEach((hop, i) => {
        doc.fontSize(10).fillColor('#1e293b')
        doc.text(`Hop ${i + 1}: ${hop.employee?.displayName || 'Unknown'} (${hop.employee?.role || 'unknown'}) — ${hop.attackType}`)
      })
    } else {
      doc.fontSize(10).fillColor('#64748b').text('No ghost hops recorded in this scenario.')
    }
    doc.moveDown(1.5)

    // Recommendations
    doc.fontSize(14).fillColor('#1e40af').text('RECOMMENDED ACTIONS')
    doc.moveDown(0.5)
    doc.fontSize(10).fillColor('#1e293b')
    doc.text('1. Mandate awareness training for all employees who clicked or submitted in this scenario')
    doc.text('2. Enable app-based 2FA — remove SMS OTP for all admin and finance roles')
    doc.text('3. Implement email gateway rules to flag external senders impersonating internal domains')
    doc.text('4. Schedule monthly simulations to track security culture score improvement')
    doc.text('5. Review cyber insurance coverage — current gap exceeds acceptable threshold')
    doc.moveDown(1.5)

    // Footer
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cbd5e1').lineWidth(1).stroke()
    doc.moveDown(0.5)
    doc.fontSize(8).fillColor('#94a3b8')
    doc.text('This report was generated by AttackSimulator. Breach cost data sourced from IBM Cost of a Data Breach Report 2023, Verizon DBIR 2023, and FBI IC3 2023. This document is confidential and intended for board-level review only.', { align: 'center' })

    doc.end()
  })
}

module.exports = { generateBoardReport }